### ISSUE TITLE
.bashrc needs update

### ISSUE THREAD

**Issue by sedghi** [wiegerthefarmer/Computing.Automaton.Tensorflow.1904#1]
I think an extra step needs to be taken for the .bashrc to be updated to point out to the installed anaconda. I did it by removing some comments that was inside my .bashrc

**Comment by wiegerthefarmer** [comment]
What did you add to your .bashrc?

**Comment by sedghi** [comment]
Nothing, my bad
I think i after I did `source ~/.bashrc` it was fixed
